# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-python/ for more details
#

version: 2.1
workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
          matrix:
            # See: https://circleci.com/docs/2.0/configuration-reference/#matrix-requires-version-21
            parameters:
              python_version: ["2.7", "3.5", "3.6"]
              debian_version: ["stretch"]
      - pypi:
          requires:
            - test
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

jobs:
  test:
    parameters:
      python_version:
        type: string
      debian_version:
        type: string

    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:<< parameters.python_version >>-<< parameters.debian_version >>
    working_directory: ~/repo<<parameters.python_version>>

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-<< parameters.python_version >>--dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-<< parameters.python_version >>-dependencies-

      - run:
          name: activate virtualenv and install dependencies.
          command: |
            test -d venv || virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-<< parameters.python_version >>-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source="." manage.py test
            coverage report --fail-under=71 -m
            pycodestyle ./eox_tenant
            pylint ./eox_tenant --rcfile=./setup.cfg
            isort --check-only --recursive --diff ./eox_tenant

  pypi:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Init .pypirc
          command: |
            echo $'[distutils]\nindex-servers = pypi\n[pypi]' > ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Prepare venv for distribution
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install twine
      - run:
          name: Create package
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Check package
          command: |
            source venv/bin/activate
            twine check dist/*
      - run:
          name: Upload to pypi
          command: |
            source venv/bin/activate
            twine upload dist/*
